---
name: apache-mesos
director_uuid: 8ff3f841-cf47-447c-9bf7-398bdd2c9cbe

releases:
- name: apache-mesos
  version: latest

compilation:
  workers: 2
  network: jenkins-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: jenkins-common
  network: jenkins-network
  size: 5
  stemcell:
    name: bosh-warden-boshlite-ubuntu-lucid-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
- name: jenkins-network
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    dns: 
    - 8.8.8.8
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    static:
      - 10.244.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
<% (29..61).each_with_index do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    dns:
    - 8.8.8.8
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>
<% (62..63).each_with_index do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    dns: 
    - 8.8.8.8
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    static:
      - 10.244.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>

jobs: 

- name: jenkins-master
  template: 
  - jenkins_master
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
    static_ips:
    - 10.244.1.14
  persistent_disk: 4096

- name: mesos-master
  template: 
  - mesos-master
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
    static_ips:
    - 10.244.1.6
  persistent_disk: 4096

- name: mesos-slave
  template: 
  - mesos-slave
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
  persistent_disk: 4096

- name: marathon
  template: 
  - marathon
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
    static_ips:
    - 10.244.1.18
  persistent_disk: 4096

- name: storm
  template: 
  - storm
  instances: 1
  resource_pool: jenkins-common
  networks:
  - name: jenkins-network
    static_ips:
    - 10.244.1.22

properties: 
  jenkins:
    admin:
      password: password
  mesos:
    network: jenkins-network
    cluster:
      name: Bosh Mesos Cluster
    zookeeper:
      ip: 10.244.1.26
      port: 2181
    master:
      ip: 10.244.1.6
      port: 5050
    slave:
      port: 5051
