final_name: bosh-jenkins-mesos
min_cli_version: 1.5.0.pre.1114
blobstore:
  provider: s3
  options:
    bucket_name: bosh-mesos
    access_key_id: AKIAIOKQDQDJHAZ2XVHQ
    encryption_key: sp$abcd123$foobar1234
